spring:
  application:
    name: dubbo3learn-provider
server:
  port: 8081
dubbo:
  # 注册中心地址
  registry:
    address: nacos://localhost:8848
    parameters:
      namespace: dev
      username: nacos
      password: nacos
    #如果不希望生成配置文件，则设置
    #注册中心作为外部元数据中心
    use-as-metadata-center: false
    #注册中心作为配置中心
    use-as-config-center: false
  # 协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受
  protocol:
    port: -1
    name: dubbo
  # 可选值 interface、instance、all，默认是 all，即接口级地址、应用级地址都注册
  application:
    register-mode: all
